version: "3"
services:
  backend:
    #build: ./calendarbackend
    image: julianstier/julianscalendarbackend:1.0
    #restart: unless-stopped
    depends_on:
      - db
    ports:
      - 8080:8080
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - DB_SOURCE=${DB_SOURCE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
  db:
    image: postgres
    #restart: unless-stopped
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - 5432:5432
    #volumes:
    #  - ./postgres-data:/var/lib/postgresql/data

  webview:
  image: julianstier/juliansangularfrontend:1.0
  #build:
  #context: ./masterthesis-angular-calendar
  #restart: unless-stopped
  ports:
  - 4200:4200
# docker-compose up --build
